### ISSUE TITLE
Code fix

### ISSUE THREAD

**Issue by RikuAzhurlar** [TeamRegular/android_vendor_lge_8916#1]
just an fyi i found a typo in your code here. check the c50-common/android.mk line 19 it states the following "ifneq ($(filter h631,$(TARGET_DEVICE)),)" which causes an issue when building for the h631 because build targets are then double called which errors out the build

**Comment by demonslayer12349** [comment]
also reading through comments on the kernel i love the whole lg needs an a$$ whooping they did the samething on my old device
